###
// get all
GET http://localhost:5000/api/beverages
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdhbWlsLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoidXNlciIsImltYWdlUGF0aCI6InNkc2RzZCJ9LCJpYXQiOjE2NjE4MDc0MjgsImV4cCI6MTY2MTgxNzQyOH0.dsYaNIK61LylgclM5AAS1O5jwSitCSXSRxWwOI_OX9o

###
// get
GET http://localhost:5000/api/beverages/5
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdhbWlsLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoidXNlciIsImltYWdlUGF0aCI6InNkc2RzZCJ9LCJpYXQiOjE2NjE4MDc0MjgsImV4cCI6MTY2MTgxNzQyOH0.dsYaNIK61LylgclM5AAS1O5jwSitCSXSRxWwOI_OX9o



###
# add
POST http://localhost:5000/api/beverages
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdhbWlsLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoidXNlciIsImltYWdlUGF0aCI6InNkc2RzZCJ9LCJpYXQiOjE2NjE5NzM4MDUsImV4cCI6MTY2MTk4MzgwNX0.OeiQi-Xa9HeKnBGfMIFoUlVZ0cZi__3Ffjtt2pDCzho



{
    "duration": 30,
    "price": 30,
    "img": "public/images/blob429a25ad-d134-49e2-bec0-9072dd00aef4",
    "name": "test",
    "category": {
        "id": 1
    }
}

###
# update
PUT http://localhost:5000/api/beverages/3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdhbWlsLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoidXNlciIsImltYWdlUGF0aCI6InNkc2RzZCJ9LCJpYXQiOjE2NjE5MjY3MjEsImV4cCI6MTY2MTkzNjcyMX0.5_L9CJmABRxaZkwzj4WKwK7bgGN2-ckSM7e5umBTkTk

{
    "duration": 35,
    "price": 30,
    "img": "public/images/7ec5a4dd661a42f7bdb32884ab8c41ea.webp"
   
    
}

###
# delete
DELETE http://localhost:5000/api/beverages/9
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdhbWlsLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoidXNlciIsImltYWdlUGF0aCI6InNkc2RzZCJ9LCJpYXQiOjE2NjE5ODcwNDgsImV4cCI6MTY2MTk5NzA0OH0.OklXeyny9r023bADQ-AyRir7I2goxKbPF6RvfLvGbBE

