###
// orders
GET http://localhost:5000/api/orders
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiSG9sYSIsInBhc3N3b3JkIjoicHJvZ3JhbW1lciJ9LCJpYXQiOjE2NTM4Nzg4MjcsImV4cCI6MTY1Mzg4ODgyN30.gaSRWtbLQjECLCZG8oH5YWPC6p5py-3--EuwTmao8v4

###
// orders
GET http://localhost:5000/api/orders/byBill/13
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiSG9sYSIsInBhc3N3b3JkIjoicHJvZ3JhbW1lciJ9LCJpYXQiOjE2NTM4Nzg4MjcsImV4cCI6MTY1Mzg4ODgyN30.gaSRWtbLQjECLCZG8oH5YWPC6p5py-3--EuwTmao8v4


###
// orders
GET http://localhost:5000/api/orders/status
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiSG9sYSIsInBhc3N3b3JkIjoicHJvZ3JhbW1lciJ9LCJpYXQiOjE2NTM4Nzg4MjcsImV4cCI6MTY1Mzg4ODgyN30.gaSRWtbLQjECLCZG8oH5YWPC6p5py-3--EuwTmao8v4



###
// orders
POST http://localhost:5000/api/orders/all
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiSG9sYSIsInBhc3N3b3JkIjoicHJvZ3JhbW1lciJ9LCJpYXQiOjE2NTM4Nzg4MjcsImV4cCI6MTY1Mzg4ODgyN30.gaSRWtbLQjECLCZG8oH5YWPC6p5py-3--EuwTmao8v4
 
 [
    {
        "price": 50,
        "duration": 70,
        "beverage": {
            "id": 1
        },
        "bill": {
            "id": 11
        }
    },
    {
        "price": 60,
        "duration": 80,
        "beverage": {
            "id": 2
        },
        "bill": {
            "id": 11
        }
    }
]